From golang:1.24

# Install curl and git
RUN apt-get update && apt-get install -y curl git && rm -rf /var/lib/apt/lists/*

# Install air
RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b /usr/local/bin

WORKDIR /app

# Only copy mod files to cache deps
COPY go.mod go.sum ./
RUN go mod download

# Let air watch live-mounted code
CMD ["air"]